practice-for-ch-rails-music-app-long-practice-main/Music_App/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show]
  resources :sources, only: [:create, :destroy, :new]


end

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/models/user.rb
class User < ApplicationRecord

    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true 
    validates :password, length: { minimum: 6}, allow_nil: true

    attr_reader :password

    after_initialize :ensure_session_token


    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        
        if user && user.is_password?(password)
            user 
        else 
            nil 
        end 
    end
     
    def password=(password) 
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end 

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end 

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end 

    def ensure_session_token 
        self.session_token ||= SecureRandom::urlsafe_base64
    end 

end

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private 

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end 

    def logged_in? 
        !!current_user 
    end 

    def cuurent_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end 





end

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
        @user = User.new
        render :new
    end 

    def create 
        @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if @user 
            login!(@user)
            redirect_to user_url(user.id)
        else 
            @user = User.new(username: params[:user][:username])
            render :now
        end
    end 

    def destroy 
        logout!
        redirect_to new_session_url
    end 





end 

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController 

    def create 
        @user = User.new(user_params)   
        if @user.save 
            login!(@user)
            redirect_to user_url(@user)
        else
            render :new 
        end
    end 

    def new 
        @user = User.new 
        render :new 
    end 

    def show 
        @user = User.new 
        render :show 
    end 
    
    private

    def user_params 
        params.require(:user).permit(:email, :password)
    end 
end 

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/layouts/users/new.html.erb
<h2>Sign Up</h2>
<form action="<%= users_url %>" method="POST">
    <label for="email">Email:
        <input type="text" id="email" name="user[email]" value="<%= @user.email%>">
    </label>
    <br/>
    <label for="password">Password:
        <input type="password" id="password" name="user[password]" value="">
    </label>
    <br/>
    <input type="submit" value="Sign Up">
</form>

practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/layouts/users/show.html.erb
<h2><%=@user.email%></h2>